version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - "8080:8080"
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://localhost:3306/newsapi
    depends_on:
      - mysqldb

    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:8.0"
    restart: always
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: newsapi
      MYSQL_USER: cinar
      MYSQL_PASSWORD: cinar-1907
      MYSQL_ROOT_PASSWORD: localhost
networks:
  springapimysql-net: